services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 2904
      POSTGRES_USER: postgres
      POSTGRES_DB: clients
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
