--liquibase formatted SQL
--changeset viktor:1
--comment:Создание таблицы клиентов
create table client_account
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    full_name   TEXT                                                NOT NULL,
    gender      VARCHAR(1),
    status      VARCHAR(20),
    create_dttm TIMESTAMP WITH TIME ZONE                            NOT NULL,
    modify_dttm TIMESTAMP WITH TIME ZONE                            NOT NULL
);
--rollback DROP TABLE client_account